//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "mod_media_type")]
pub enum ModMediaType {
    #[sea_orm(string_value = "image")]
    Image,
    #[sea_orm(string_value = "youtube")]
    Youtube,
}
